### ISSUE TITLE
How to generate the pose image from an input image?

### ISSUE THREAD

**Issue by xuanyuzhang21** [haofanwang/ControlNet-for-Diffusers#2]
Hi~, thanks for your great work! I was wondering how to generate the pose image from an input image. thanks for your help.

**Comment by haofanwang** [comment]
@xuanyuzhang21 Thanks for your interest!

There is no constrain, for developers, you can load any pre-trained pose detector (like OpenPose, or from MMPose). Or if you just want to test with several images, you can also directly use [this demo](https://huggingface.co/spaces/hysts/ControlNet) to generate pose and just download the pose result.

**Comment by xuanyuzhang21** [comment]
Thanks for your quick reply!

**Comment by haofanwang** [comment]
One thing you should take case is that I find ControlNet may be sensitive to pose format as it is trained with OpenPose samples. So it is recommended to use their suggested pose estimator.
