### ISSUE TITLE
convert script missing ?

### ISSUE THREAD

**Issue by xyyeah** [haofanwang/ControlNet-for-Diffusers#25]
Thanks for your greate job ! I have some problems to convert the model to diffusers. When i finished cloning the [diffusers](https://github.com/takuma104/diffusers.git), I switched into the branch "controlnet", but couldnot find a script `convert_controlnet_to_diffusers.py` under `~/diffusers/scripts`. Could you help me to figure it out ?

**Comment by haofanwang** [comment]
Please do `git checkout 9a37409663a53f775fa380db332d37d7ea75c915` @xyyeah

**Comment by xyyeah** [comment]
Noted & Thanks~
