### ISSUE TITLE
Runtime Error due to Shape Mismatching when Replacing Base Model with SD1.5 Inpainting

### ISSUE THREAD

**Issue by leminhhin** [haofanwang/ControlNet-for-Diffusers#29]
Dear @haofanwang,

I am writing to report an issue that I encountered while following the steps to replace the base model with SD1.5 inpainting in your repository. Specifically, I edited the path as instructed and ran the script python tool_transfer_control.py.

```
path_sd15 = './models/v1-5-pruned.ckpt'
path_sd15_with_control = './models/control_sd15_scribble.pth'
path_input = './models/sd-v1-5-inpainting.safetensors'
path_output = './models/control_sd-v1-5-inpainting_scribble.pth'
```

However, I faced a runtime error related to shape mismatching. I believe that the error is caused by the fact that the base model (Stable Diffusion 1.5) only has 4 input channels, while the inpainting model (Stable Diffusion 1.5 inpainting) has 9 input channels.

Therefore, I would greatly appreciate it if you could advise me on how to resolve this issue. Thank you in advance for your assistance.

Best regards,

![image](https://user-images.githubusercontent.com/91191855/223759399-e78bbe20-5105-45cb-92a6-5f901860a21e.png)
![image](https://user-images.githubusercontent.com/91191855/223759779-b318caa0-83d2-4da6-8975-756ea739bc16.png)

**Comment by haofanwang** [comment]
You cannot use the inpainting model directly as the input dimension is different. If you want to equip ControlNet with inpainting ability, please follow [this section](https://github.com/haofanwang/ControlNet-for-Diffusers#controlnet--inpainting). @leminhhin

**Comment by leminhhin** [comment]
I was able to equip ControlNet with inpainting following your guidance. Much appreciated!
