### ISSUE TITLE
Issue with diffusers models

### ISSUE THREAD

**Issue by jschoormans** [haofanwang/ControlNet-for-Diffusers#7]
Thanks for putting this manual together!
Unfortunately, I cant find the script convert_controlnet_to_diffusers anywhere, not in the PR. 
Could you help me with this? Thanks!

**Comment by ghpkishore** [comment]
Hey, it got updated in the latest commit. It seems to be a WIP commit, try to git clone the commit before the current one. This commit ID should work: 9a37409663a53f775fa380db332d37d7ea75c915

**Comment by jschoormans** [comment]
Thank you so much!!!!

Op vr 24 feb. 2023 om 13:32 schreef Garimella Hari Pawan Kishore <
***@***.***>:
